# Generated by Django 4.0 on 2023-11-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=30000),
        ),
    ]
