# Generated by Django 4.0 on 2023-11-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0004_person_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
