# Generated by Django 4.0 on 2023-11-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0006_alter_person_table_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fuel',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fueltype', models.ManyToManyField(to='appp.FuelType')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
