# Generated by Django 4.0 on 2023-11-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0007_fueltype_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='fueltype',
            field=models.ManyToManyField(related_name='models', to='appp.FuelType'),
        ),
    ]
