# Generated by Django 4.0 on 2023-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_publication_name_alter_book_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'file_upload',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_name',
            field=models.CharField(choices=[('pb1', 'Publication 1'), ('pb2', 'Publication 2'), ('pb3', 'Publication 3'), ('pb4', 'Publication 4')], max_length=3, null=True),
        ),
    ]
